version: '3.8'

services:
  # PostgreSQL Database (Supabase yerine local kullanmak isterseniz)
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: discord_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot_network

  # Redis (Cache için)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - bot_network

  # Web Panel
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/discord_bot
    depends_on:
      - postgres
      - redis
    networks:
      - bot_network
    volumes:
      - .:/app
      - /app/node_modules

  # Discord Bot
  bot:
    build: .
    command: npm run bot
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/discord_bot
    depends_on:
      - postgres
      - redis
    networks:
      - bot_network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  bot_network:
    driver: bridge
